apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
        app: mongo-express
  template:
    metadata:
      labels:
        editor: vscode
        app: mongo-express
    spec:
      containers:
      - name: main
        image: mongo-express
        resources: {}
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: test
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: test
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: test