load('ext://helm_remote', 'helm_remote')

helm_remote(
  'mysql',
  repo_name='bitnami',
  repo_url='https://charts.bitnami.com/bitnami',
  values='./values.yaml'
)

k8s_resource(
  "mysql:statefulset",
  port_forwards=port_forward(
    23306,
    container_port=3306,
    name='mysql',
  )
)