load('ext://helm_remote', 'helm_remote')
load('../../Tiltfile_common', 'port_forward_host')

helm_remote(
  'mysql',
  repo_name='bitnami',
  repo_url='https://charts.bitnami.com/bitnami',
  values='./values.yaml'
)

k8s_resource(
  "mysql",
  port_forwards=port_forward(
    23306,
    container_port=3306,
    name='mysql',
    host=port_forward_host
  )
)