load('ext://helm_remote', 'helm_remote')
load('../../Tiltfile_common', 'port_forward_host')

helm_remote(
  'etcd',
  repo_name='bitnami',
  repo_url='https://charts.bitnami.com/bitnami',
  values='./values.yaml'
)

k8s_resource(
  "etcd",
  port_forwards=port_forward(
    22379,
    container_port=2379,
    name='etcd',
    host=port_forward_host
  )
)
