load('ext://helm_remote', 'helm_remote')

helm_remote(
  'minio',
  repo_name='minio',
  repo_url='https://charts.min.io/',
  values='./values.yaml'
)

k8s_resource(
  "minio:deployment:default",
  port_forwards=[
    port_forward(
      29000,
      container_port=9000,
      name='minio',
    ),
    port_forward(
      29001,
      container_port=9001,
      name='minio-console',
    ),
  ]
)
