# https://github.com/minio/minio/tree/master/helm/minio

fullnameOverride: minio

rootUser: "admin"
rootPassword: "testtest"

mode: standalone

resources:
  requests:
    memory: 1Gi

persistence:
  enabled: false

users:
  - accessKey: test
    secretKey: testtest
    policy: consoleAdmin

buckets:
  - name: test
    policy: none