load('../../Tiltfile_common', 'port_forward_host')

yaml = helm(
  'neo4j-standalone',
  name='neo4j',
  values='./values.yaml'
)
k8s_yaml(yaml)

k8s_resource(
  "neo4j",
  port_forwards=[
    port_forward(
      27687,
      container_port=7687,
      name='neo4j',
      host=port_forward_host
    ),
    port_forward(
      27474,
      container_port=7474,
      name='neo4j-browser',
      host=port_forward_host
    ),
  ]
)