# https://github.com/neo4j/helm-charts/blob/5.13.0/neo4j/values.yaml
neo4j:
  name: neo4j
  password: secretpassword
  edition: "community"
  acceptLicenseAgreement: "no"
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      accessModes:
        - ReadWriteOnce
      requests:
        storage: 5Gi
services:
  neo4j:
    spec:
      type: ClusterIP
