load('ext://helm_remote', 'helm_remote')

helm_remote(
  'phpmyadmin',
  repo_name='bitnami',
  repo_url='https://charts.bitnami.com/bitnami',
  values='./values.yaml'
)

k8s_resource(
  "phpmyadmin",
  port_forwards=port_forward(
    30001,
    container_port=8080,
    name='phpmyadmin',
  ),
  resource_deps=['mysql:statefulset']
)